package.json, src/runtime.js
* replacing QAjax with fetch;
* supporting websocket actions;
* supporting w/ and w/o browser;
* adding 'setInstanceKnowledge' function;
* adding 'getInstanceKnowledge' function;
* merging 'internalUpdate' into 'doUpdate';
* adding google authentication function;
* adding logs on errors;
* renaming sim by instance;
* renaming entity by agent;
* removing all references to 'constants';
=> Updating js binding:

lib/createInstance.js, lib/errors.js, lib/index.js, package.json, src/createInstance.js, src/errors.js, src/index.js, test/helper.js, test/mocha.opts, test/test_createAgent.js, test/test_createInstance.js, test/test_errors.js, test/test_getAgentKnowledge.js, test/test_update.js
- Introducing error types
- Adding several unit tests
=> Improving errors

API.md, package.json, src/createInstance.js, src/index.js, src/onExit.js, src/request.js, test/test_createAgent.js, test/test_createInstance.js, test/test_getAgentKnowledge.js, test/test_update.js
By making sure all the destruction at exit are synchronous
=> Fixing issues with `destroyOnExit`

package.json, src/createInstance.js, src/ws.js, test/browser/webpack.config.js
And completely disabling it on browser environments
=> Updating to the newer version of 'ws'

.eslintignore, .eslintrc, package.json
=> Now relying on the shared eslint configuration

.eslintignore, README.md, src/client.js, src/defaults.js, test/.eslintrc, test/browser/.eslintrc, test/browser/helper.js, test/browser/webpack.config.js, test/nodejs/helper.js, test/test_addAgentContextOperations.js, test/test_computeAgentDecision.js, test/test_createAgent.js, test/test_errors.js
=> Agent operations addition autobatching

README.md, package.json, src/client.js, src/index.js, test/browser/test.js, test/test_addAgentContextOperations.js, test/test_computeAgentDecision.js, test/test_getAgentDecisionTree.js
connects to craft-ai/craft-ai-client-js#24
=> Using the local interpreter

DEVELOPERS.md
* Indented and added lines before and after code blocks to fix steps numbering
=> Fixed steps numbering in DEVELOPERS.md

src/context.js, src/decide.js, src/time.js, test/test_context.js, test/test_time.js
=> client js can handle periodic values

src/client.js, test/test_addAgentContextOperations.js
=> throwing error on sending no operation or invalid operations

test/.eslintrc, test/browser/.eslintrc, test/browser/helper.js, test/browser/webpack.config.js, test/nodejs/helper.js, test/test_addAgentContextOperations.js, test/test_computeAgentDecision.js, test/test_createAgent.js, test/test_getAgent.js, test/test_getAgentDecisionTree.js, test/test_getAgentInspectorUrl.js, test/test_listAgents.js
Should allow multiple build to be run concurrently.
+ Adding some tests to try to reproduce a bug that does not exists it seems.
=> per-build agent ids in tests

src/client.js
@cloderic please review
Connects to #58
=> fix public url

test/nodejs/helper.js
Which is more unique than TRAVIS_BUILD_ID (should be unique per platform)
Connects to #71
=> Using TRAVIS_JOB_ID

package.json, src/client.js, src/defaults.js, src/errors.js, test/browser/test.js, test/mocha.opts, test/test_addAgentContextOperations.js, test/test_createClient.js
Let's not forget to update the documentation afterward
=> Now reading the given jwt token for owner, project and platform

src/decide.js, test/test_createClient.js, test/test_errors.js, test/test_interpreterSuite.js
_connects to #69_
⚠️ Do not merge before craft-ai/craft-ai-interpreter-test-suite#6 ⚠️
=> More tests in 'decide'

src/decide.js
⚠️ merge  craft-ai/craft-ai-interpreter-test-suite#7 before ⚠️
=> Fixing the day_of_week range

src/time.js, test/test_time.js
=> Fix generated day_of_week range

package.json, src/time.js, test/test_time.js
=> Smarter taking into account of moment instances in Time

src/decide.js
=> add "default" validator that trigger the warning

src/index.js
@cloderic  @PierreSalaun please review
=> export properties to be used outside

src/properties.js, test/test_properties.js
=> Use isDate instead of instanceof moment

src/client.js, src/defaults.js, test/test_addAgentContextOperations.js
=> Disabling the operations addition buffer

CHANGELOG.md, src/client.js, src/constants.js, test/test_addAgentContextOperations.js, test/test_createAgent.js, test/test_getAgent.js
=> Filter invalid id at the agent creation

CHANGELOG.md, src/time.js, test/test_time.js
=> Time can be created from a floating point timestamp

CHANGELOG.md, src/client.js, test/test_addAgentContextOperations.js
[This part of the code](https://github.com/craft-ai/craft-ai-client-js/pull/103/files#diff-cf27c1d543e886c89cd9ac8b8aeaf05bL151) was unreachable and a request was issued with no operations.
Rejecting the promise seems unnatural.
=> Fix adding empty `Array` of operations

scripts/update_version.sh
- Previous version was causing issues leading to crappy thing such as craft-ai/craft-ai-client-js@2f670695d0f70e7dc986b47450d1806dc6fead76
=> Fix the update version script

CHANGELOG.md, package.json, src/client.js, src/index.d.ts, test/test_createAgent.js
=> TypeScript type definitions

CHANGELOG.md, src/client.js, src/index.d.ts, src/request.js, test/data/configuration_1_operations_2.json, test/test_addAgentContextOperations.js, test/test_getAgentContextOperations.js
⚠️ Getting ready for an upcoming release of the craft ai API ⚠️ 
Fixes #108
=> Get agent context operations pagination support

CHANGELOG.md, src/client.js, src/index.d.ts, src/index.js, src/interpreter.js, src/parse.js, test/test_decideFromContextsArray.js, test/test_getDecisionRulesProperties.js, test/test_interpreterSuite.js
> Merge craft-ai/craft-ai-interpreter-test-suite#11 and commit the change first
Fixes #115 and #116
=> Interpreter improvements

package.json
@matthieu-boussard please review
Connects to #118
=> update debug version

CHANGELOG.md, README.md, src/client.js, src/index.d.ts, test/test_getAgentStateHistory.js, test/test_getAgentStatesHistory.js
=> get agent state history

.travis.yml, CHANGELOG.md, src/client.js, src/defaults.js, src/errors.js, src/request.js, test/.eslintrc, test/browser/helper.js, test/data/configuration_2.json, test/mocha.opts, test/nodejs/helper.js, test/test_errors.js, test/test_getAgentDecisionTree.js
=> Handling tree computation timeouts

CHANGELOG.md, test/test_addAgentContextOperations.js, test/test_computeAgentDecision.js, test/test_createClient.js, test/test_decideFromContextsArray.js, test/test_errors.js, test/test_getAgentDecisionTree.js, test/test_getAgentStateHistory.js, test/test_getDecisionRulesProperties.js, test/test_listAgents.js, test/test_properties.js
=> Remove context extrapolation in text

CHANGELOG.md, test/test_addAgentContextOperations.js
=> Fixing addContextOperations test

src/client.js, src/constants.js, test/test_getAgentDecisionTree.js
=> adding tree version support

CHANGELOG.md, src/constants.js, test/test_bulk.js
Also minor fixes for bulk tests.
=> Updating client to have tree v2 by default

CHANGELOG.md, src/interpreter_v2.js
Minor fix on authorized types error message.
=> Minor fix on authorized types error message

CHANGELOG.md, test/.mocharc.js, test/data/configuration_2.json, test/data/expected/configuration_1_operations_1.json, test/data/expected/configuration_1_operations_2.json, test/test_addAgentContextOperations.js, test/test_getAgentContextOperations.js, test/test_getAgentDecisionTree.js, test/test_getGeneratorContextOperations.js
With last update on the contextOps, some tests were failing.
Fix these tests.
=> Fix failing tests for complete context ops

CHANGELOG.md, package-lock.json, package.json, src/client.js, src/polyfill.js, test/test_addAgentContextOperations.js, test/test_bulk.js, test/test_getAgentContextOperations.js, test/test_getAgentDecisionTree.js, test/test_getAgentStateHistory.js, test/test_getGeneratorContextOperations.js, test/test_missing_values.js
Axelle:
This PR needs beta to be updated with the fix on kafka.
=> Bulk generator JS client

CHANGELOG.md, src/interpreter_v2.js, test/data/configuration_mv.json, test/test_getDecisionRulesProperties.js
Related to: https://github.com/craft-ai/craft-ai/issues/3157
=> Chore remove is_optional in javascript

.travis.yml, package.json, scripts/clean_up.js
Related to: craft-ai/craft-ai#2633
=> Add a clean_up session after test round on travis

CHANGELOG.md, src/client.js, test/data/configuration_1.json, test/data/configuration_1_generator.json, test/data/configuration_2.json, test/data/configuration_mv.json, test/test_bulk.js, test/test_getSingleWindowScoreBulk.js, test/test_getSlidingWindowScoresBulk.js, test/test_score.js
Jira issue: https://craft-ai.atlassian.net/browse/CRAI-3436?atlOrigin=eyJpIjoiZTc1MGIxOWEwNzcxNGIyNzhjOTI0NzJmMmU4ODkyMzQiLCJwIjoiaiJ9
=> Added validation score functions
